name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Build the pages with fastn
        run: |
          fastn build --base=${{ github.event.repository.name }}
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: ./.build
