name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Build the pages with fastn
        run: |
          fastn build --base=${{ github.event.repository.name }}
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./.build
